// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkbdleuybftlqnpvhoqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYmRsZXV5YmZ0bHFucHZob3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTAxMjIsImV4cCI6MjA3MTMyNjEyMn0.DX7GfO-KLTEWDp-JbSKlM-V1aeyRYGEoWOCBuKW1jgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});